### ISSUE TITLE
CMake does not work if no build type is specified

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/project-template#6]
efd3d21b49b31fc3cd79c0cd160a235275ad929c introduces changing CMakeBuildType to upper case. However if no build type is specified the string operation fails.

Jenkins did not catch this because it always specifies a build type.

Either introduce a check or revert this commit. I think we have multiple places where the exact upper-lower case of the build type is required. If you keep it carefully grep that you don't miss any to really make it work.

**Comment by vargheseg** [comment]
>> [efd3d21](https://github.com/ChimeraTK/project-template/commit/efd3d21b49b31fc3cd79c0cd160a235275ad929c) introduces changing CMakeBuildType to upper case

This should not be true; content inside `CMAKE_BUILD_TYPE` would not be changed

**Comment by vargheseg** [comment]
The issue is, on the invocation below we have an error:

```
cmake ../
CMake Error at CMakeLists.txt: (string):
  string no output variable specified
```
This is caused by missing  `"` around `CMAKE_BUILD_TYPE` and consequently the string command ends up with one argument when `CMAKE_BUILD_TYPE` is not set. Intended behavior is to invoke `string` with an empty string and output variable as parameters in this case.

bd0bfc3aef9938f5c9ab9134d97ef0725ec90ee3 should fix this.
